### ISSUE TITLE
Console commands not working because of the session

### ISSUE THREAD

**Issue by aircokol** [nilsenpaul/npeditmultipleelements#2]
Hi, 
your plugin breaks any usage of the console commands because of the **session initialization** in plugin **init** method

```bash
$ php ./craft/app/etc/console/yiic help jobsboard
CException: Property "Craft\ConsoleApp.session" is not defined. in /app/craft/app/framework/base/CComponent.php:130
Stack trace:
#0 /app/craft/app/framework/base/CModule.php(105): CComponent->__get('session')
#1 /app/craft/plugins/npeditmultipleelements/services/NpEditMultipleElementsService.php(34): CModule->__get('session')
#2 /app/craft/plugins/npeditmultipleelements/NpEditMultipleElementsPlugin.php(33): Craft\NpEditMultipleElementsService->handleNonEditRequests()
#3 /app/craft/app/services/PluginsService.php(152): Craft\NpEditMultipleElementsPlugin->init()
#4 /app/craft/app/etc/console/ConsoleApp.php(86): Craft\PluginsService->loadPlugins()
#5 /app/craft/app/framework/base/CApplication.php(170): Craft\ConsoleApp->init()
#6 /app/craft/app/framework/YiiBase.php(121): CApplication->__construct(Array)
#7 /app/craft/app/etc/console/yiic.php(86): YiiBase::createApplication('Craft\\ConsoleAp...', '/app/craft/app/...')
#8 /app/craft/app/etc/console/yiic(4): require_once('/app/craft/app/...')
#9 {main}
```

you will need to add some checks which _mode_ app is running before init the session.

**Comment by nilsenpaul** [comment]
Just fixed this by adding craft()->isConsole() to the init function. Thanks for your feedback!
